from .services import router as service_router
from .hotels import router as hotel_router
from .hotel_images import router as hotel_images_router
from .hotel_services import router as hotel_services_router
from .hotel_staff import router as hotel_staff_router
from .auth import router as auth_router
from .users import router as user_router
from .rooms import router as room_router
from .room_services import router as room_services_router
from .room_images import router as room_images_router
from .room_beds import router as room_beds_router
from .bookings import router as booking_router
from .cart import router as cart_router