"""add address fields to hotels

Revision ID: 89ce66b0cf56
Revises: 863d1e258ebe
Create Date: 2026-06-25 18:43:18.323621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ce66b0cf56'
down_revision: Union[str, Sequence[str], None] = '863d1e258ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('hotels', sa.Column('city', sa.String(length=150), nullable=False))
    op.add_column('hotels', sa.Column('address', sa.String(length=150), nullable=False))
    op.add_column('hotels', sa.Column('zip_code', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'zip_code')
    op.drop_column('hotels', 'address')
    op.drop_column('hotels', 'city')
    op.drop_column('hotels', 'country')
    # ### end Alembic commands ###
